### ISSUE TITLE
Ordering of leave buttons

### ISSUE THREAD

**Issue by stefonarch** [elviosak/plugin-wingmenu#1]
First of all thanks a lot for the effort!

This is not really an issue but I see that the buttons shutdown, hibernate and so one are alphabetically ordered like the menu and the categories, so in different languages the ordering changes quite randomly. 

A default  ordering could be from bottom up (or top down) "shutdown - reboot - hibernate - suspend- logout".

Or make  ordering/removal (lxqt-leave, hibernate) by D&D possible?

**Comment by elviosak** [comment]
I was planning on doing something like that, but probably not D&D, with how it is structured it would need to rebuild the sidebar when reordering, so it wouldn't work right.
My plan is to add some options in config to remove some buttons or add some custom ones, but it's a bit complex because it would need to work well when changing menu files.

**Comment by stefonarch** [comment]
> it's a bit complex because it would need to work well when changing menu files.

I  noticed that menu files are well considered, with the "simple" menu the config center ends up between "about" and "lock". Maybe just ignore all the leave desktop files from menu file?

**Comment by elviosak** [comment]
Added [here](https://github.com/slidinghotdog/plugin-wingmenu/commit/78f607dea3618d4c1d571e0d6d22563d6af7ad05), files are copied and managed by the plugin.
